### ISSUE TITLE
Service binding operator crashes if encountered a unknown field in SBR spec

### ISSUE THREAD

**Issue by pratikjagrut** [redhat-developer/service-binding-operator#702]
*If SBR contains the unknown field in spec then the operator goes into panic error eventually crashing it.*

**Expected behaviour**: Handling unknown field gracefully or pruning them while applying SBR.
**Actual behaviour**: Operator crashes.

**Below is the SBR I applied:**

```
apiVersion: operators.coreos.com/v1alpha1
kind: ServiceBinding
metadata:
    name: service-binding
spec:
    database:
        group: service.example.com
        version: v1
        kind: Backserv
        name: demo-backserv-cr-1
```

**Logs:**

```
2020-10-01T16:08:18.068+0530    DEBUG   sbrcontroller.buildSBRPredicate Create Predicate        {"GKV": "operators.coreos.com/v1alpha1, Kind=ServiceBinding", "reconcile": true}
2020-10-01T16:08:18.069+0530    DEBUG   mapper  current resource is a SBR       {"Object.Namespace": "test-namespace-6712", "Object.Name": "service-binding", "Requests": [{"Namespace":"test-namespace-6712","Name":"service-binding"}]}
2020-10-01T16:08:18.069+0530    INFO    reconciler      Reconciling ServiceBinding...   {"Request.Namespace": "test-namespace-6712", "Request.Name": "service-binding"}
2020-10-01T16:08:18.555+0530    DEBUG   reconciler      Found service binding request to inspect        {"Request.Namespace": "test-namespace-6712", "Request.Name": "service-binding", "ServiceBinding.Name": "service-binding"}
E1001 16:08:18.556251   73606 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 856 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x14defe0, 0x23fbcc0)
        /home/pjagrut/go/src/github.com/redhat-developer/service-binding-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /home/pjagrut/go/src/github.com/redhat-developer/service-binding-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82
panic(0x14defe0, 0x23fbcc0)
        /usr/local/go/src/runtime/panic.go:969 +0x166
github.com/redhat-developer/service-binding-operator/pkg/controller/servicebinding.(*reconciler).Reconcile(0xc0007269c0, 0xc0007884a0, 0x13, 0xc0004432d0, 0xf, 0x0, 0xbfd58a468421a71c, 0xc00023c5a0, 0xc00023c518)
        /home/pjagrut/go/src/github.com/redhat-developer/service-binding-operator/pkg/controller/servicebinding/reconciler.go:122 +0x520
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000746d80, 0x15371e0, 0xc000382420, 0x0)
        /home/pjagrut/go/src/github.com/redhat-developer/service-binding-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:256 +0x161
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000746d80, 0xc0006d4700)
        /home/pjagrut/go/src/github.com/redhat-developer/service-binding-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:232 +0xae
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc000746d80)
        /home/pjagrut/go/src/github.com/redhat-developer/service-binding-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:211 +0x2b
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000562990)
        /home/pjagrut/go/src/github.com/redhat-developer/service-binding-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x5f
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000562990, 0x3b9aca00, 0x0, 0x1, 0xc0007aa3c0)
        /home/pjagrut/go/src/github.com/redhat-developer/service-binding-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc000562990, 0x3b9aca00, 0xc0007aa3c0)
        /home/pjagrut/go/src/github.com/redhat-developer/service-binding-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
        /home/pjagrut/go/src/github.com/redhat-developer/service-binding-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:193 +0x305
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x138ca10]

goroutine 856 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /home/pjagrut/go/src/github.com/redhat-developer/service-binding-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x105
panic(0x14defe0, 0x23fbcc0)
        /usr/local/go/src/runtime/panic.go:969 +0x166
github.com/redhat-developer/service-binding-operator/pkg/controller/servicebinding.(*reconciler).Reconcile(0xc0007269c0, 0xc0007884a0, 0x13, 0xc0004432d0, 0xf, 0x0, 0xbfd58a468421a71c, 0xc00023c5a0, 0xc00023c518)
        /home/pjagrut/go/src/github.com/redhat-developer/service-binding-operator/pkg/controller/servicebinding/reconciler.go:122 +0x520
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000746d80, 0x15371e0, 0xc000382420, 0x0)
        /home/pjagrut/go/src/github.com/redhat-developer/service-binding-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:256 +0x161
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000746d80, 0xc0006d4700)
        /home/pjagrut/go/src/github.com/redhat-developer/service-binding-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:232 +0xae
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc000746d80)
        /home/pjagrut/go/src/github.com/redhat-developer/service-binding-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:211 +0x2b
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000562990)
        /home/pjagrut/go/src/github.com/redhat-developer/service-binding-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x5f
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000562990, 0x3b9aca00, 0x0, 0x1, 0xc0007aa3c0)
        /home/pjagrut/go/src/github.com/redhat-developer/service-binding-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc000562990, 0x3b9aca00, 0xc0007aa3c0)
        /home/pjagrut/go/src/github.com/redhat-developer/service-binding-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
        /home/pjagrut/go/src/github.com/redhat-developer/service-binding-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:193 +0x305
FATA[0141] Failed to run operator locally: failed to run operator locally: failed to exec []string{"build/_output/bin/service-binding-operator-local", "--zap-level=debug", "--zap-encoder=console", "--zap-level", "2"}: exit status 2 
make: *** [Makefile:370: local] Error 1
```

**Comment by isutton** [comment]
I've seen this before when `services` is empty, which is the case of your input file. Would you double check that? Adding `services: []`  should work that around, and I believe https://github.com/redhat-developer/service-binding-operator/pull/698 touches that specifically.

Also, could you add the branch and commit you're building from?

**Comment by pedjak** [comment]
Fixed in https://github.com/redhat-developer/service-binding-operator/pull/698
